# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeaccesscontrol',
            name='all_hosts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safeaccesscontrol',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='safeaccesscontrol',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
