# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='name',
            field=models.CharField(help_text='dotted-path key for this secret', max_length=256),
        ),
    ]
