# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_auto_20160615_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMonitoringException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored', models.BooleanField(help_text='force monitored (True) or unmonitored (False)')),
                ('start', models.DateTimeField(help_text='when should this exception begin?')),
                ('end', models.DateTimeField(help_text='when should this exception end?')),
                ('host', models.ForeignKey(help_text='host to create exception for', on_delete=django.db.models.deletion.CASCADE, to='environments.Host')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='monitored',
            field=models.BooleanField(default=False, help_text='should new hosts in this environment be monitored by default?'),
            preserve_default=False,
        ),
    ]
