# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_auto_20160718_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='matches salt state name', max_length=256, unique=True),
        ),
    ]
