# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_auto_20160819_1609'),
        ('environments', '0004_auto_20160805_1413'),
    ]

    operations = [
    ]
