# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the grain', max_length=256)),
                ('value', models.CharField(help_text='the value for the grain', max_length=256)),
                ('host', models.ForeignKey(help_text='host to assign grain to', on_delete=django.db.models.deletion.CASCADE, to='environments.Host')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='safe',
            unique_together=set([('name', 'vault')]),
        ),
    ]
