# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-05 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_auto_20161103_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(help_text='FQDN', max_length=256, unique=True),
        ),
    ]
