# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 22:29
from __future__ import unicode_literals

import dewey.core.utils
import dewey.environments
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0007_auto_20170405_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kind',
            field=enumfields.fields.EnumField(enum=dewey.environments.ClusterType, max_length=10),
        ),
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=enumfields.fields.EnumField(enum=dewey.environments.OperatingSystem, max_length=10),
        ),
        migrations.AlterField(
            model_name='vault',
            name='vault_protocol',
            field=enumfields.fields.EnumField(enum=dewey.core.utils.ProtocolEnum, max_length=10),
        ),
    ]
