# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 17:21
from __future__ import unicode_literals

import dewey.core.utils
import dewey.environments
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0008_auto_20170420_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kind',
            field=enumfields.fields.EnumIntegerField(enum=dewey.environments.ClusterType),
        ),
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=enumfields.fields.EnumIntegerField(enum=dewey.environments.OperatingSystem),
        ),
        migrations.AlterField(
            model_name='vault',
            name='vault_protocol',
            field=enumfields.fields.EnumIntegerField(enum=dewey.core.utils.ProtocolEnum),
        ),
    ]
