# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:38
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import hardware


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20151006_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetassignment',
            name='depth',
            field=django_enumfield.db.fields.EnumField(blank=True, default=1, enum=hardware.RackDepth, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetassignment',
            name='orientation',
            field=django_enumfield.db.fields.EnumField(blank=True, default=1, enum=hardware.RackOrientation, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='interconnect',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hardware.SwitchInterconnect),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='speed',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hardware.SwitchSpeed),
        ),
    ]
