#!/bin/bash -eu

. /usr/share/debconf/confmodule

for template in {settings_module,db_host,db_port,db_user,db_password,jira_user,jira_password,pdns_uri,pdns_key,vault_password}; do
    db_input medium dewey/${template}
    db_go
done
