# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_squashed_0009_auto_20170421_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=128)),
                ('change_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Highstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('return_code', models.IntegerField()),
                ('jid', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.Host')),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('highstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.Highstate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('highstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.Highstate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='change',
            name='state_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.StateChange'),
        ),
    ]
