# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='change_content',
            new_name='content',
        ),
    ]
