# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0002_auto_20170519_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='highstate',
            name='received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
