# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0003_highstate_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='highstate',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
