# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hosts


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20160511_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('regular_expression', models.CharField(max_length=256)),
                ('match_field', django_enumfield.db.fields.EnumField(default=1, enum=hosts.MatchField)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='a friendly name for this vault', max_length=256)),
                ('url', models.URLField(help_text='base URL to vault, e.g. https://vault.sfo.plos.org:8200')),
                ('transit_key_name', models.CharField(max_length=256)),
                ('token_path', models.CharField(help_text='filesystem path to valid vault token', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='addressassignment',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_assignments', to='hosts.Host'),
        ),
        migrations.AlterField(
            model_name='addressassignment',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_assignments', to='hosts.Network'),
        ),
        migrations.AddField(
            model_name='sharedsecret',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Vault'),
        ),
        migrations.AddField(
            model_name='hostsecret',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Vault'),
        ),
    ]
