# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20160511_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressassignment',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_assignments', to='hosts.Host'),
        ),
        migrations.AlterField(
            model_name='addressassignment',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_assignments', to='hosts.Network'),
        ),
        migrations.AlterField(
            model_name='host',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_host', to='contenttypes.ContentType'),
        ),
    ]
