# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0016_auto_20160527_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsecret',
            name='name',
            field=models.CharField(default='secret', max_length=256),
        ),
        migrations.AddField(
            model_name='sharedsecret',
            name='name',
            field=models.CharField(default='secret', max_length=256),
        ),
    ]
