# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_auto_20160527_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='token_path',
        ),
        migrations.AddField(
            model_name='vault',
            name='token_variable',
            field=models.CharField(default='VAULT_TOKEN', help_text='environment variable containing token', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostsecret',
            name='name',
            field=models.CharField(help_text='dotted-path key for this secret', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedsecret',
            name='name',
            field=models.CharField(help_text='dotted-path key for this secret', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='name',
            field=models.CharField(help_text='a friendly name for this vault', max_length=256, unique=True),
        ),
    ]
