# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 18:30
from __future__ import unicode_literals

from django.db import migrations


def migrate_clusters(apps, schema_editor):
    Cluster = apps.get_model('hosts', 'Cluster')
    EnvCluster = apps.get_model('environments', 'Cluster')
    EnvHost = apps.get_model('environments', 'Host')

    for cluster in Cluster.objects.all():
        cluster_members = []
        for member in cluster.members.all():
            env_member = EnvHost.objects.get(id=member.id)
            cluster_members.append(env_member)
        new_cluster = EnvCluster(id=cluster.id, name=cluster.name, description=cluster.description, kind=cluster.kind)
        new_cluster.save()
        for member in cluster_members:
            new_cluster.members.add(member)


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_auto_20160609_1528'),
    ]

    operations = [
        migrations.RunPython(migrate_clusters)
    ]
