# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 21:57
from __future__ import unicode_literals

from django.db import migrations


def migrate_networks(apps, schema_editor):
    Network = apps.get_model('hosts', 'Network')
    NetNetwork = apps.get_model('networks', 'Network')

    for network in Network.objects.all():
        new_network = NetNetwork(
            id=network.id,
            slug=network.slug,
            description=network.description,
            cidr=network.cidr,
            interface_id=network.interface_id
        )
        new_network.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0018_auto_20160610_1130'),
        ('networks', '0001_initial')
    ]

    operations = [
        migrations.RunPython(migrate_networks)
    ]
