# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 22:57
from __future__ import unicode_literals

from django.db import migrations


def delete_hosts_objects(apps, schema_editor):
    AddressAssignment = apps.get_model('hosts', 'AddressAssignment')
    Cluster = apps.get_model('hosts', 'Cluster')
    Host = apps.get_model('hosts', 'Host')
    HostRole = apps.get_model('hosts', 'HostRole')
    Network = apps.get_model('hosts', 'Network')
    ReservedAddressBlock = apps.get_model('hosts', 'ReservedAddressBlock')

    for host in Host.objects.all():
        host.delete()
    for role in HostRole.objects.all():
        role.delete()
    for cluster in Cluster.objects.all():
        cluster.delete()
    for assign in AddressAssignment.objects.all():
        assign.delete()
    for reserved in ReservedAddressBlock.objects.all():
        reserved.delete()
    for net in Network.objects.all():
        net.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_auto_20160610_1531'),
    ]

    operations = [
        migrations.RunPython(delete_hosts_objects)
    ]
