# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_squashed_0012_auto_20170421_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerdistributionunit',
            name='name',
            field=models.SlugField(),
        ),
    ]
