# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 22:29
from __future__ import unicode_literals

import dewey.hardware
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20160511_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetassignment',
            name='depth',
            field=enumfields.fields.EnumField(blank=True, enum=dewey.hardware.RackDepth, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetassignment',
            name='orientation',
            field=enumfields.fields.EnumField(blank=True, enum=dewey.hardware.RackOrientation, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='interconnect',
            field=enumfields.fields.EnumField(enum=dewey.hardware.SwitchInterconnect, max_length=10),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='speed',
            field=enumfields.fields.EnumField(enum=dewey.hardware.SwitchSpeed, max_length=10),
        ),
    ]
