# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 17:21
from __future__ import unicode_literals

import dewey.hardware
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_auto_20170420_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetassignment',
            name='depth',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=dewey.hardware.RackDepth, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetassignment',
            name='orientation',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=dewey.hardware.RackOrientation, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='interconnect',
            field=enumfields.fields.EnumIntegerField(enum=dewey.hardware.SwitchInterconnect),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='speed',
            field=enumfields.fields.EnumIntegerField(enum=dewey.hardware.SwitchSpeed),
        ),
    ]
